---
- hosts: all
  serial: 1
  gather_facts: false
  tasks:
    - name: touch file
      file: path=/tmp/foo.conf state=touch
   
    - name: sleep 5
      command: sleep 5

    - name: run command
      command: echo "hello" >  /tmp/hello.txt
